### ISSUE TITLE
Put Nano Adblocker on AMO as well

### ISSUE THREAD

**Issue by LiCybora** [LiCybora/NanoCoreFirefox#15]
Some users do not happy with the extra configuration on uBO with ND and just want NA to install and forget as they used in other browser. Before the goal achieve, the following has to be done:

- [ ] Patch innerHTML assignment in ace.js
- [x] Handle integration with ND
- [x] Grant official permission from upstream
- [x] Not applying Chromium specific patch

The first one can be update acejs to v1.4.2, but it create another issue that I am unwilling to deal with. Require manually grab innerHTML assignement removal commits and apply to v1.2.9 (currently in use in upstream).

The second one is likely I trapped myself as the ND from GitHub hosted and AMO using different extension ID (currently, NA from here will not auto-enable integration during ND on AMO is installed). I still need a GitHub hosted version to take care the existing user, so will create new version of NA on AMO. For simplicity, NA in AMO will only integrate ND from AMO and vice versa. If user download one from AMO and one from GitHub....then good luck for them to manually enable integration list.

I will ask for the permission once everything are ready.

The final one is done but require double check.

**Comment by LiCybora** [comment]
After reviewing many even more nasty extension on AMO, I guess the first one can be skipped until Mozilla have objection.

**Comment by ghajini** [comment]
Hello @LiCybora
Would you like pls work on this
`https://github.com/gorhill/uBlock/issues/1890` ,may be a pull request to gorhill.....

Also work here is stalled `https://github.com/NanoAdblocker/NanoCore/issues/33`

UI of ublock origin/nanoadblocker should resemble new material design of new androids and NOT the old android 4

**Comment by LiCybora** [comment]
Why not just open a new issue?

However, I don't have an Android now. I am also busy for other things recently. So, the priority for this will be lowered.
