### ISSUE TITLE
Not Compatible with windscribe addon

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [LiCybora/NanoCoreFirefox#18]
### Describe the issue (Required)
Both nano adblocker and ublockorigin are not compatible with windscribe vpn addon,
If i enable both extensions at the same time and restart my browser the current tab will refresh itself automatically. 
### Reproduction Steps 
-->
Install windscribe addon
And sigin and then restart your browser

### Anything else you believe to be useful
Maybe windscribe also disable ads that's why it is not compatible with other adblockers

#### Environment (Required)

- Operating System and Version: windows 10
- Browser and Version: firefox x64 66.0.3
- Nano Adblocker Version: latest
- Nano Defender Version (Optional if you are not using it): latest

#### Your filter lists (Required)

Default settings only

**Comment by LiCybora** [comment]
Nothing about adblocker. I can reproduce even without nano/ubo (only windscribe). My guess is that VPN extension refresh your tab after its connection done.

But even so, the refresh only take place once during browser restart and seems not a big deal or trouble maker.

**Comment by Ashutosh-Kukreti** [comment]
Ok thank you,
Well I’ve removed the windscribe addon because it was really irritating that whenever I type something in my browser (after launching it) it is used to disapper after 5 seconds.
