### ISSUE TITLE
Text cannot be long pressed for copy/paste/select on Android

### ISSUE THREAD

**Issue by LiCybora** [LiCybora/NanoCoreFirefox#19]
This is a continuation of NanoAdblocker/NanoCore#130
### Describe the issue (Required)
Neither copy nor paste can be chosen in editor of `My filters`. Even selecting a single line of rule is usually problematic (either nothing can be selected, or everything are selected).

### Screenshots (Required)
Later or see from link above.

### Screenshot of console (Required, press `F12` to open the console)
Later.

### URLs where this issue occurs (Required if applicable)
None.

### Reproduction Steps (Optional if trivial)
1. Open `My filters` in Nano Adblocker on Firefox Android
2. Long click any rules or comment, or even empty space, wondering why everything are highlighted but no option for copy/paste (or either nothing can be highlighted).

### Anything else you believe to be useful (Optional)
Only occurs in `My filters` but not `My rules`, `Whitelist` or any advance setting.

#### Environment (Required)

- Operating System and Version: Android P
- Browser and Version: Firefox 66.0.5
- Nano Adblocker Version: 1.0.0.109
- Nano Defender Version (Optional if you are not using it): Not important

**Comment by ghajini** [comment]
Any luck in fixing....
While keyboard(Gboard, anysoftkeyboard, Swiftkey keyboard) doesn't open at advanced settings when you are trying to edit ...... firefox android

**Comment by LiCybora** [comment]
The advanced settings should not be affected since this is a issue caused by a bug in ace,js, which is used in `My filters` for syntax highlighting. I cannot reproduce on my device with Gboard.

I may try if new version of ace.js can resolve problem, but their issue ticket is still opened and likely no luck on that.

**Comment by LiCybora** [comment]
With acejs 1.4.11, the problem is partially resolved.

Still... long press does not behave as expected, but at least user able to highlight text when long press and drag.

copy/paste options still not comes up with long press, but an extra option menu exist:
![image](https://user-images.githubusercontent.com/40160522/82961916-457d5d80-9ff1-11ea-9db2-c498b13ccdbc.png)
![image](https://user-images.githubusercontent.com/40160522/82962004-837a8180-9ff1-11ea-93ba-02685d876323.png)
![image](https://user-images.githubusercontent.com/40160522/82962103-d0f6ee80-9ff1-11ea-9dce-a55be0248851.png)

This also somehow workaround the issue that `My filters` editor lacking a searchbox on Android as "Ctrl+F" is hard to trigger on mobile device.

Changes will be applied to next version once confirmed stable.
