### ISSUE TITLE
Nano Adblock is not working properly

### ISSUE THREAD

**Issue by shinstimulateshinstimulate** [LiCybora/NanoCoreFirefox#21]
### Describe the issue (Required)
Firefox Version of Nano Adblock is not blocking all ads and does not display the number of blocked ads

### Screenshots (Required)

![image](https://user-images.githubusercontent.com/51929596/59633304-7d76f200-914c-11e9-8f55-0118638b86d0.png)

![image](https://user-images.githubusercontent.com/51929596/59634416-04c56500-914f-11e9-9bd3-852976418bfd.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/51929596/59633437-bfa03380-914c-11e9-9fa5-2fc961fb0222.png)

### URLs where this issue occurs (Required if applicable)

https://www.youtube.com/watch?v=O4irXQhgMqg as an example

#### Environment (Required)

- Operating System and Version: Win 10 ver 1809
- Browser and Version: 67.0.2 (64-bit)
- Nano Adblocker Version: Nano Adblocker 1.0.0.116
- Nano Defender Version (Optional if you are not using it): currently disabled

#### Your filter lists (Required)

All filters that come with nano adblocker except regionals ones

Nano Defender Integration​​​
Nano filters​​​
Nano filters – Annoyance​​​
Nano filters – Whitelist​​​
uBlock filters​​​
uBlock filters – Annoyances​​​
uBlock filters – Badware risks​​​
uBlock filters – Experimental​​​​​
uBlock filters – Privacy​​​
uBlock filters – Resource abuse​​​
uBlock filters – Unbreak​​ 
Adblock Warning Removal List​​​
AdGuard Base List​​​​
AdGuard Mobile Ads​​​​
EasyList​​​
Nano contrib filter – Placeholder buster​​​​​
AdGuard Tracking Protection​​
EasyPrivacy​​​
Fanboy's Enhanced Tracking List​
Malvertising filter list by Disconnect​​​​​​​
Malware Domain List
Malware domains​
AdGuard Annoyances​​​
AdGuard Social Media​​​
Anti-Facebook List​​​
Fanboy's Annoyance List​​​
Fanboy's Cookie List​​​
Fanboy's Social Blocking List
Dan Pollock's hosts file​
hpHosts' Ad and tracking servers​​​
NoCoin Filter List​​​
Peter Lowe's Ad and tracking server list​

#### Your custom filters (Required if you have any)

youtube.com#@#.ytp-ce-element
youtube.com#@#.video-annotations
youtube.com#@#.ytp-cards-teaser
youtube.com#@#.ytp-ce-playlist

**Comment by winneratwin** [comment]
I think I know the issue to this(and a tep fix). it has to do with the adguard filters. basically you have to uninstall nano adblocker and enable everything other then those two.(if you enable them you can't just disable them and that will be all good go ahead and try, I did.) and i was on here to create the post but eh guess i can answer to this post. idk whats gone wrong with the adguard filters that's so bad that it breaks nano adblocker?

**Comment by LiCybora** [comment]
Thanks for reporting. Seems there is regression in 1.0.0.116, and it is fine to work with adguard in previous version.

**Comment by LiCybora** [comment]
@jspenguin2017 The extended options patch broken.

**Step To Reproduce**
1. Subscribe any filters with extended options (e.g.: Adguard base filter)
2. Update filter, wondering it keep showing error for adguard base filter.
3. Adblocker stop working.

**Screenshots**
![image](https://user-images.githubusercontent.com/40160522/59731400-895fd280-9278-11e9-9a14-db914f89ddb6.png)

![image](https://user-images.githubusercontent.com/40160522/59731165-acd64d80-9277-11e9-86bc-e3e12d0aac6a.png)
![image](https://user-images.githubusercontent.com/40160522/59731333-3a19a200-9278-11e9-93b8-903e3d0da583.png)

**Anything else you believe to be useful (Optional)**
![image](https://user-images.githubusercontent.com/40160522/59731219-d8593800-9277-11e9-92cf-2284f5387e74.png)
`opts` is disappear in ubo v1.20.0

**Comment by jspenguin2017** [comment]
Eh... I need unit tests...

**Comment by jspenguin2017** [comment]
@LiCybora Fixed in tip-of-tree. The massive refactoring coming from upstream is causing me a lot of problems recently... I need a proper testing solution to make sure new builds are not going to have regression...

**Comment by LiCybora** [comment]
v1.0.0.117 is published for urgent fix. Awaiting for someone confirm the fix.

**Comment by xlollomanx** [comment]
@LiCybora seems ok for me in new version

**Comment by LiCybora** [comment]
Thanks, close as fixed.
