### ISSUE TITLE
Heads up about recent repository changes

### ISSUE THREAD

**Issue by jspenguin2017** [LiCybora/NanoCoreFirefox#23]
I find myself spending over half an hour a day just to handle the day to day maintenance of my projects, and I want to change that. I want to have time to actually develop my projects, especially with Manifest V3 changes coming, my current setup is nowhere near ready to handle that. 

As a first step, I will start to use Renovate to manage dependencies. I am receiving a dozen vulnerability alerts from GitHub every week, although I don't believe any of them is true positive, having noise in vulnerability reports is not very good. 

I will be automating more and more of my daily maintenance tasks through GitHub Apps, Continuous Integration, and NanoMeow. These changes will probably not affect you, this is just a heads up so you know what will be coming.

**Comment by LiCybora** [comment]
Thanks for the mention. The vulnerability report also alert me as well. Your automation might also help for it. Will heads up in future to prevent potential regression.
