### ISSUE TITLE
v1.0.0.122 is ready for test! 

### ISSUE THREAD

**Issue by jspenguin2017** [LiCybora/NanoCoreFirefox#24]
v1.0.0.122 is ready for test. Due to the large amount of changes, make sure to clean existing build output as the build scripts do not automatically handle that. In general, I recommend to do a clean for every version update. 

Let me know if something blows up.

**Comment by LiCybora** [comment]
Terminal warning:
```
WARN: Line '        chain = chain.slice(pos + 1);' becomes much shorter when trimmed
WARN: Line '            window[prop] = noopfn;' becomes much shorter when trimmed
```

Sanity check passed. Might publish soon.

**Comment by jspenguin2017** [comment]
Don't publish yet, there's ~~a regression~~ two regressions detected upstream. Need to repin to ~~1.21.4~~ 1.21.6.

**Comment by jspenguin2017** [comment]
Actually they don't affect Firefox. OK, if you think it's good then feel free to release. I need to repin on my side.

**Comment by jspenguin2017** [comment]
As for the terminal warnings, it's fine. I checked the code, it's just an extra space. Safe to ignore. 

They are fixed here: https://github.com/gorhill/uBlock/commit/a89aad030412d0470ca845565059286ce57971b5
Those warnings should go away in the next version.

**Comment by LiCybora** [comment]
v1.0.0.122 for Firefox is published.

**Comment by krystian3w** [comment]
Linter no detect ABP / Brave / AdGuard 'syntax' "names" scriplets without `.js`:

``js
com##+js(ra, class|id|style)
``

**Comment by jspenguin2017** [comment]
@krystian3w The linter only supports Nano Adblocker's filter syntax, the latest beta version should support script snippets without `.js`.

**Comment by jspenguin2017** [comment]
@krystian3w Actually, you're right, the linter can handle aliases but not implicit `.js`. I noted it down, will fix before releasing production build: https://github.com/NanoAdblocker/NanoCore/issues/271#issuecomment-514845444

**Comment by jspenguin2017** [comment]
The issue with linter is fixed.
