### ISSUE TITLE
Bad updates.json

### ISSUE THREAD

**Issue by krystian3w** [LiCybora/NanoCoreFirefox#25]
#24 - changed to minimalize risk?

```
  "browser_specific_settings": {
    "gecko": {
      "id": "{0f929014-5ed2-4527-8b8d-86a9c889b129}",
      "update_url": "https://github.com/LiCybora/NanoCoreFirefox/issues",
      "strict_min_version": "55.0"
    }
  }
}
```

should be one from these:

```
https://github.com/LiCybora/NanoCoreFirefox/raw/master/Extension%20Compiler/updates.json

https://raw.githubusercontent.com/LiCybora/NanoCoreFirefox/master/Extension%20Compiler/updates.json
```

**Comment by krystian3w** [comment]
As for now I cannot found moddified XPI with bad url, also maybe notepad++ siltent put this into file (misclicks).

**Comment by LiCybora** [comment]
Don't worry. All released XPI are signed. If you do not touch `xpinstall.signatures.required`, Firefox will prevent you install it. Even you disable it, a warning message will still alert you before you can install it.

Just remember don't download from somewhere else not mentioned from this repository.
