### ISSUE TITLE
[1.0.0.130] addon no add option in right context menu

### ISSUE THREAD

**Issue by krystian3w** [LiCybora/NanoCoreFirefox#27]
### Describe the issue (Required)

Addon after update no add "block element" in right click menu.

### Screenshots (Required)

`N/A`

### Screenshot of console (Required, press `F12` to open the console)

`N/A`

### URLs where this issue occurs (Required if applicable)

`N/A`

### Reproduction Steps (Optional if trivial)

`N/A`

### Anything else you believe to be useful (Optional)

`N/A`

#### Environment (Required)

- Operating System and Version: `Windows 7 Pro`
- Browser and Version: `FX 70.0.1`
- Nano Adblocker Version: `1.0.0.130`
- Nano Adblocker installed from: `Mozilla store`

#### Your filter lists (Required)

`N/A`

#### Your custom filters (Required if you have any)

`N/A`

**Comment by LiCybora** [comment]
Fixed at LiCybora/NanoCore2@07cfbff I forgot this is a separated repository.

Menu should come back in next version, which should be release very soon.
