### ISSUE TITLE
lequipe.fr

### ISSUE THREAD

**Issue by DiaoulDu** [LiCybora/NanoCoreFirefox#29]
### Describe the issue (Required)

lequipe.fr does not show the same infos wether or not nano adblocker is enabled. This can be verified accessing https://www.lequipe.fr /Football/ and following the link "Voir les directs" which is supposed to give in real-time the evolution of score during games. When nano adblocker is enabled the scores are sticky and remain live when desabling nano adb. 
### Screenshot of console (Required, press `F12` to open the console)
[Nano] Nano Defender Activated :: www.lequipe.fr core.js:43:24
[Nano] Excluded :: uBO-Extra rules-common.js:306:28
Échec du chargement pour l’élément <script> dont la source est « https://www.lequipe.fr/js/app.f565b1b62be6a2c5cdd0.js ». Football:1127:1
Échec du chargement pour l’élément <script> dont la source est « https://www.lequipe.fr/js/vendors.f565b1b62be6a2c5cdd0.js ».

#### Environment (Required)

- Operating System and Version:  Windows 10
- Browser and Version: FF 72.0.1
- Nano Adblocker Version: 1.0.0.134
- Nano Defender Version (Optional if you are not using it):  15.0.0.177

#### Your filter lists (Required)
standard filters only.

**Comment by LiCybora** [comment]
Let me know if the situation is right.

Without Nano Adblocker, all scores will keep up-to-date? Because what I see is that the site is updated every 5 minutes instead of real-time update. Even with Nano Adblocker on, I still get updated.

I am luckily capture the moment it is updating (with red logo in the middle) The screenshot is with Nano Adblocker open.
![image](https://user-images.githubusercontent.com/40160522/72951859-e1405800-3dca-11ea-8415-050fd2e7eb38.png)

Also the screenshot of logger (hidden hours for not exposure timezone):
![image](https://user-images.githubusercontent.com/40160522/72951956-34b2a600-3dcb-11ea-8ceb-7ee550075124.png)

If what you mean is that without Nano, it will update in real-time instead of 5 minutes base, then I cannot reproduce since even without Nano, I also got 5 minutes update intervals.

**Comment by DiaoulDu** [comment]
thanx for answering.
I will give you more details during the next saturday (a lot of games), imho when using nano Adblocker,
the scores are not updated at all.
Cheers.

**Comment by DiaoulDu** [comment]
Hello LiCybora,
to reproduce the failure, I've done the following :

- erase my FireFox install
- get a new FireFox
- access to https://www.lequipe.fr/Directs , there are some games in progress and the scores are ok.
- install **Nano AdBlocker,** the scores are still ok
- install **Nano Defender**, the scores ARE NOT OK
- uninstall **Nano AdBlocker**, the scores ARE OK.

So, reporting to Nano AdBlocker is relevant BUT the cohabitation between the two nanos seemto
involved.

First image at 14:13, as you see the game in spain is in progress

![withoutNanoAdBlocker](https://user-images.githubusercontent.com/8970219/73121840-daf2dd00-3f7e-11ea-8e1b-554ce22cf431.png)

five minutes later, with both nanos installed, the game in spain seems not to have begun.

![WithNanoAdBlocker](https://user-images.githubusercontent.com/8970219/73121844-de866400-3f7e-11ea-8e8f-77085e23244b.png)

and finaly, if I get rid of Nano AdBlocker only, it runs but of course Nano Defender alone does nothing and may be the problem is on the Defender side.
This does not occur when using chrome.

Cheers.

**Comment by DiaoulDu** [comment]
and last, using both uBlock Origin and Nano Defender is ok.

**Comment by LiCybora** [comment]
Sorry, I cannot reproduce. All scores are still updated in 5 minutes interval (just like my previous screenshot with logo show up when updating). My previous screenshot is with ND (just hidden in toolbar).

Can you screenshot your logs and console? You may compare the logger with mine to see if there is sth should not be blocked but blocked.

**Comment by DiaoulDu** [comment]
Many thanx, unfortunately I guess I have some problem in my user land i.e. currently I only use
ublock-origin and it works a while, then after may be half an hour I reach other failures due to "Cross-Origin Request blocked" (I don't know why).
So You can close, I need to work on my side to find what is going wrong.
Thanx again.
