### ISSUE TITLE
Possible signing issue 1.0.0.148 Disabled By Browser

### ISSUE THREAD

**Issue by mikeloeven** [LiCybora/NanoCoreFirefox#32]
### Describe the issue (Required)
Firefox Android disabled nano ad block after the update with a signature verification error requiring a manual override in about:config to get it working again

### Screenshots (Required)
![Screenshot_2020-05-30-18-57-36](https://user-images.githubusercontent.com/2266606/83340554-b9489000-a2a7-11ea-8852-3fa0f2a25ced.png)

#### Environment (Required)

- Operating System and Version: Android 6.0.1
- Browser and Version: Firefox 68.8.1 
- Nano Adblocker Version: 1.0.0.148
- Nano Defender Version (Optional if you are not using it): 15.0.0.199

**Comment by LiCybora** [comment]
I cannot reproduce. Maybe something there are corruption during downloading update.

Try backup, uninstall it and re-install it again to see if issue happen?

**Comment by mikeloeven** [comment]
Redownloading the extension has resolved the signing issue
