### ISSUE TITLE
allow (green) rules is always available in future nano defender version?

### ISSUE THREAD

**Issue by gabri25ele** [LiCybora/NanoCoreFirefox#34]
From uBlock Origin 1.28 is no longer possible to point-and-click to create allow (green) rules from within the popup panel.
Is there any chance that this feature will remain in Nano Defender? or are we too closed to the base code?

**Comment by LiCybora** [comment]
Nano **Defender** never have that feature. I guess you mean Nano **Adblocker**.

Unless the Chromium developer change his mind to not follow upstream changes, mostly likely we will follow changes.

> From uBlock Origin 1.28 is no longer possible to point-and-click to create allow (green) rules from within the popup panel.

It is possible. There are two ways for that. From release note of 1.28.0 it said:

> You can get back temporarily the ability to create allow rules from within the popup panel by **tapping twice the `Ctrl` key**....you can recover the ability to create allow rules by **changing the advanced setting `filterAuthorMode` to true**.

**Comment by gabri25ele** [comment]
sorry, my error, yes, I mean Nano Adblocker!
