### ISSUE TITLE
Uptade to v1.0.0.153 required

### ISSUE THREAD

**Issue by Corshi** [LiCybora/NanoCoreFirefox#38]
As of now, NanoCore is in version v1.0.0.153
Features:
- **→ Updated script snippets and web accessible resources ←**
- Updated filters
- Cherry-picked gorhill@d49a9dc

**Comment by LiCybora** [comment]
I need to re-consider the project status. I will perform the update as of features in upcoming weekend.

As the project upstream's developer is changed, and neither the original or new developer mention their stance for this port, I am not sure whether I will continue to maintain the project for the unknown developer. Perhaps I will wait one more week for their response before deciding what to do next.
